const keywordsData = `KeywordsEN,KeywordsFR
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, previous, courses, transfer, requirements, equivalency, training records, mandatory training curriculum, foundational training curriculum","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, précédent, cours, transfère, exigence, équivalence, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, previous, courses, transfer, requirements, equivalency, training records, mandatory training curriculum, foundational training curriculum, update","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, précédent, cours, transfère, exigence, équivalence, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, transfère, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, délai"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long, week, status, pending, complete","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, transfère, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, délai, semaine, statut, en attente, terminé"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, courses, training, mandatory training curriculum, foundational training curriculum, complete, alternate, alt, version, accessibility, accessible","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, cours, formation, curriculum de formation obligatoire, curriculum de formation fondamentale, terminé, alternative, alt, version, accessibilité, accessible"
"technical difficulties, profile, support, course, training, assistance, issue, solutions, system error, application, Saba, LMS, troubleshoot, help","difficulté technique, profil, soutien, cours, formation, assistance, problème, solutions, erreur système, application, Saba, SGA, résolution de problème, aide"
"manager, team leader, director, profile, support, course, training, assistance, issue, system error, application, Saba, LMS, help, search, cannot find, access","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, problème, erreur système, application, Saba, SGA, aide, recherche, je ne peux pas trouver, introuvable, accès"
"manager, team leader, director, profile, support, course, training, assistance, issue, system error, application, Saba, LMS, help, search, cannot find, access, privilege, role, approval, permission, need","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, problème, erreur système, application, Saba, SGA, aide, recherche, je ne peux pas trouver, introuvable, accès, privilège, rôle, approbation, autorisation, besoin"
"profile, how long, issue, session, active, application, Saba, LMS, inactivity, duration, timeout, connection, platform, disconnect","profil, combien de temps, problème, session, active, application, Saba, SGA, inactivité, durée, délai d’expiration, connexion, plateforme, déconnexion"
"manager, new, team leader, director, profile, support, course, training, assistance, issue, system error, application, Saba, LMS, help, search, cannot find, access, privilege, role, approval, permission, need, how, add, member, team, account, team dashboard","gestionnaire, nouveau, nouvelle, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, problème, erreur système, application, Saba, SGA, aide, recherche, je ne peux pas trouver, introuvable, accès, privilège, rôle, approbation, autorisation, besoin, comment, ajouter, membre, équipe, compte, console d’équipe"
"content, uploader, profile, courses, training, class, Saba, admin, administrator, upload, import, job aid, access, role, privilege, support, training material, design team, files, add, process","contenu, téléverseur, profil, cours, formation, classe, Saba, admin, administrateur, téléverser, télécharger, aide-mémoire, accès, rôle, privilège, soutien, matériel de formation, équipe de conception, fichiers, ajouter, processus"
"content, uploader, profile, courses, training, class, Saba, admin, administrator, upload, import, job aid, access, role, privilege, support, training material, design team, fichier, add, process, get","contenu, téléverseur, profil, cours, formation, classe, Saba, admin, administrateur, téléverser, télécharger, aide-mémoire, accès, rôle, privilège, soutien, matériel de formation, équipe de conception, files, ajouter, processus, obtenir"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long, week, status, pending, complete, data, completion, account","FO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, transfère, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, délai, semaine, statut, en attente, terminé, données, réussite, compte"
"manager, team leader, director, profile, support, course, training, assistance, employee, exhausted, attempt, test, passing, add, try, issue, application, Saba, LMS, help, fail, additional, exam","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, employé, épuisé, tentative, test, réussir, ajouter, essaie, problème, application, Saba, SGA, aide, échoué, supplémentaire, examen"
"manager, team leader, director, profile, support, course, training, assistance, employee, exhausted, attempt, test, passing, add, try, issue, application, Saba, LMS, help, fail, additional, exam, learner, approval, obtain, request","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, employé, épuisé, tentative, test, réussir, ajouter, essaie, problème, application, Saba, SGA, aide, échoué, supplémentaire, examen, apprenant, approbation, obtenir, demande"
"MTC, FTC, curricula, curriculum, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long, status, pending, complete, data, completion, account, reconciliation, learning, indigenous","CFO, CFF, curricula, curriculum, programme d’études, profil, obligatoire, fondamentale, ministère, Dept, cours, transfert, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, achèvement, délai, statut, en attente, terminé, données, réussite, compte, réconciliation, apprentissage, autochtone"
"account, username, login information, profile, support, course, training, assistance, issue, system, error, application, Saba, LMS, troubleshoot, help, access, login, credentials","compte, nom d’utilisateur, information de connexion, profil, soutien, cours, formation, assistance, problème, erreur, système, application, Saba, SGA, résolution de problème, aide, accès, connexion, identifiants"
"course, training, find, search, catalog, Saba, register, assistance, system, application, Saba, LMS, help, support, ways","cours, formation, trouver, recherche, catalogue, Saba, inscrire, assistance, système, application, Saba, SGA, aide, soutien, façons"
"technical difficulties, profile, support, course, training, assistance, issue, solutions, application, Saba, LMS, troubleshoot, help, launching test, launching course, account, incomplete, blocking, technical issue, progress","difficulté technique, profil, soutien, cours, formation, assistance, problème, solutions, application, Saba, SGA, résolution de problème, aide, lancer le test, lancer le cours, compte, incomplet, obstacle, problème technique, progrès"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, mandatory training curriculum, foundational training curriculum, completion, status, pending, complete, data, completion, account, technical difficulties, profile, support, course, training, assistance, issue, solutions, application, troubleshoot, help, launching course, account, incomplete, blocking, technical issue, progress","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, curriculum de formation obligatoire, curriculum de formation fondamentale, complété, statut, en attente, terminé, données, réussite, compte, difficulté technique, profil, soutien, cours, formation, assistance, problème, solutions, application, résolution de problème, aide, lancer le cours, compte, incomplet, obstacle, problème technique, progrès"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, mandatory training curriculum, foundational training curriculum, completion, status, complete, data, completion, account, profile, support, course, training, assistance, help, account, incomplete, manager, new, team leader, director, profile, support, course, training, assistance, application, Saba, LMS, help, search, access, privilege, role, member, team, account, team dashboard, report","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, curriculum de formation obligatoire, curriculum de formation fondamentale, complété, statut, terminé, données, réussite, compte, difficulté technique, profil, soutien, cours, formation, assistance, aide, compte, gestionnaire, nouveau, nouvelle, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, application, Saba, SGA, aide, recherche, accès, privilège, rôle, membre, équipe, compte, console d’équipe, rapport"
"MTC, FTC, curricula, curriculum, profile, mandatory, foundational, , courses, mandatory training curriculum, foundational training curriculum, completion, status, complete, data, completion, account, profile, support, course, training, assistance, help, account, incomplete, manager, new, team leader, director, profile, support, course, training, assistance, application, Saba, LMS, help, search, access, privilege, role, member, team, account, team dashboard, report, employee, analytics, accurate, accuracy","CFO, CFF, curricula, curriculum, programme d’études, profil, obligatoire, fondamentale, cours, curriculum de formation obligatoire, curriculum de formation fondamentale, complété, statut, terminé, données, réussite, compte, difficulté technique, profil, soutien, cours, formation, assistance, aide, compte, gestionnaire, nouveau, nouvelle, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, application, Saba, SGA, aide, recherche, accès, privilège, rôle, membre, équipe, compte, console d’équipe, rapport, employé, analytique, précis, précision"
"course, class, link, share, sharing, deeplink, Saba, LMS, help, search, curriculum, curricula, certification, URL, send, copy link","cours, classe, lien, partage, partager, lien profond, deeplink, Saba, SGA, aide, recherche, curriculum, certification, URL, envoyer, lien copié"
"course, class, link, share, sharing, deeplink, Saba, LMS, help, search, curriculum, curricula, certification, URL, send, copy link, manager, Team lead, team","cours, classe, lien, partage, partager, lien profond, deeplink, Saba, SGA, aide, recherche, curriculum, certification, URL, envoyer, lien copié, gestionnaire, chef d’équipe, équipe"
"course, class, link, share, sharing, deeplink, Saba, LMS, help, search, curriculum, curricula, certification, URL, send, copy link, Admin, administrator, Saba, certification, curriculum, curricula, learners, guide, send","cours, classe, lien, partage, partager, lien profond, deeplink, Saba, SGA, aide, recherche, curriculum, certification, URL, envoyer, lien copié, admin, administrateur, Saba, certification, curriculum, apprenants, guider, envoyer"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, previous, courses, transfer, requirements, equivalency, training records, mandatory training curriculum, foundational training curriculum, added, manager, team lead, lead","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, précédent, cours, transfère, exigence, équivalence, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, ajouter, gestionnaire, chef d’équipe, chef"
"error, profile, account, Saba, personal, information, learner, update, support, help, correct, correction, data, change, email, name, email address, need","erreur, profil, compte, Saba, personnel, information, apprenant, mise à jour, soutien, aide, corriger, correction, données, modifier, changer, nom, courriel, adresse courriel, besoin"
"return, department, Dept, learner, access, leave, account, Saba, assistance, help, absence, sick, reactivation, close, disactivate, recovery, username","retour, ministère, Dept, apprenant, accès, depart, compte, Saba, assistance, aide, absence, maladie, réactivation, fermer, désactivé, récupération, nom d’utilisateur"
"course, class, link, Saba, LMS, help, search, copy link, Saba, learners, bookmark, favorites, access, URL, website, add, hyperlink, shortcut","cours, classe, lien, Saba, SGA, aide, recherche, envoyer, lien copié, Saba, apprenants, signet, favoris, accès, URL, site web, ajouter, mettre, hyperlien, raccourci"
"class, learner, course, Saba, language, preference, support, change, update, platform, access, registration, remove registration, changer, modify","classe, apprenant, cours, Saba, langage, langue, préférence, soutien, changer, mise à jour, mettre à jour, plateforme, accès, enregistrement, retirer inscription, changer, modifier"
"manager, team leader, team lead, request, class, course, approval, learner, support, registered, registration, access, pending approval, approval request, supervisor","gestionnaire, chef d’équipe, demande, classes, cours, approbation, apprenant, soutien, enregistré, enregistrement, accès, inscription, demande d’approbation en attente, demande d’approbation, superviseur"
"manager, team leader, team lead, request, class, course, approval, learner, support, registered, registration, access, pending approval, approval request, supervisor, employee","gestionnaire, chef d’équipe, demande, classes, cours, approbation, apprenant, soutien, enregistré, enregistrement, accès, inscription, demande d’approbation en attente, demande d’approbation, superviseur, employé"
"remove, employee, team, team dashboard, manager, team leader, team lead, supervisor, my team, support, Saba, modify, how","retirer, employé, équipe, console d’équipe, gestionnaire, chef d’équipe, superviseur, mon équipe, soutien, Saba, modifier, comment"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, requirements, equivalency, mandatory training curriculum, foundational training curriculum, manager, team lead, lead, training, complete, learner, support","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, cours, exigence, équivalence, curriculum de formation obligatoire, curriculum de formation fondamentale, gestionnaire, chef d’équipe, chef, formation, complété, apprenant, soutien"
"Saba, access, personal, home, computer, government, network, off the network, internet, support, login, remote access, security, connect, connection, external, private network, private, VPN", "Saba, accès, personnel, maison, de la maison, ordinateur, gouvernement, réseau, hors réseau, internet, soutient, connexion, accès à distance, sécurité, connexion, connecter, externe, réseau privé, privé, VPN"
"evaluation, course, class, complete, pending, completed, completion status, status, completion, support, review, requirements, profile, feedback, expired, training","évaluation, cours, classe, complété, en attente, statut d’achèvement, statut, achèvement, soutien, vérification, exigences, profil, rétroaction, expiré, formation"
"employee, team, team dashboard, manager, team leader, team lead, supervisor, my team, support, Saba, modify, how, approve, learning, training, course, class, learner, registration, reject, pending approval","employé, équipe, console d’équipe, gestionnaire, chef d’équipe, superviseur, mon équipe, soutien, Saba, modifier, comment, approuver, apprentissage, formation, cours, classe, apprenant, inscription, rejeter, en attente d’approbation"
"Saba, iService, support, access, information, page, intranet, help, tools, assistance, online resources","Saba, iService, soutien, accès, information, page, intranet, aide, outils, assistance, ressource en ligne"
"Saba, course, admin, administrator, instructor, facilitator, role, privilege, steps, support, help, to take, training","Saba, cours, admin, administrateur, formateur, facilitateur, rôle, privilège, étapes, soutien, aide, de suivre, formation"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, requirements, equivalency, mandatory training curriculum, foundational training curriculum, manager, team lead, lead, training, complete, learner, support, information, employee","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, cours, exigence, équivalence, curriculum de formation obligatoire, curriculum de formation fondamentale, gestionnaire, chef d’équipe, chef, formation, complété, apprenant, soutien, information, employé, responsable"
"job aid, job-aid, tool, manager, team lead, team leader, lead, help, support, resources","aide mémoire, aide-mémoire, outils, gestionnaire, chef d’équipe, chef, aide, soutien, ressources, responsable"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, requirements, mandatory training curriculum, foundational training curriculum, manager, team, lead, training, completion, learner, support, information, employee, data, team dashboard","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, cours, exigence, curriculum de formation obligatoire, curriculum de formation fondamentale, gestionnaire, équipe, formation, achèvement, apprenant, soutien, information, employé, responsable, données, console d’équipe"
"proxy, assign, manager, director, actions, on my behalf, authorization, process, support, instructions, role, privilege, reports, executive, EX, act as","mandataire, assigner, gestionnaire, directeur, actions, en mon nom, autorisation, processus, soutien, instructions, rôle, privilège, rapport, cadre, exécutif, EX, agir en tant que"
"proxy, assign, manager, director, actions, on my behalf, authorization, process, support, instructions, role, privilege, reports, executive, EX, act","mandataire, assigner, gestionnaire, directeur, actions, en mon nom, autorisation, processus, soutien, instructions, rôle, privilège, rapport, cadre, exécutif, EX, agir en tant que"
"team member, team, learning, activity, plan, learning plan, employee, learner, manager, team lead, team leader, course, class, training, how, process, add","membre de l’équipe, équipe, apprentissage, activité, plan, plan d’apprentissage, employé, apprenant, gestionnaire, responsable, chef d’équipe, cours, classe, formation, comment, processus, ajouter"
"learner, job aid, job-aid, find, support, tools","apprenant, aide mémoire, aide-mémoire, trouver, soutien, outils"
"waitlist, accept, reject, drop, seat, learner, available, approval, request, pending, registration, how to, class, course","liste d’attente, accepter, rejeter, abandonner, siège, apprenant, disponible, approbation, demande, en attente, inscription, comment, classe, cours"
"access, Saba, first time, account, profile, learner, login, instructions, credentials, support, help, assistance, steps, password, username, session, PS, PeopleSoft, new","accès, Saba, première fois, compte, profil, apprenant, connexion, instructions, identifiants, soutien, aide, assistance, étapes, mot de passe, nom d’utilisateur, session, PS, PeopleSoft, nouveau"
"accessibility, activate, turn on, support, feature, assistance, interface, user, learner, profile, account, accessibility mode, tools","accessibilité, activer, soutien, fonctionnalité, assistance, interface, utilisateur, apprenant, profil, compte, mode d’accessibilité, outils"
"external, course, class, outside of Saba, externally, add, tool, how, completed, completed learning, learning, process, learner, completed course, training","externe, cours, classe, a l’extérieur de Saba, ajouter, outil, comment, complété, apprentissage complété, apprentissage, processus, apprenant, cours complété, formation"
"language, preference, profile, account, learner, how, change, update, settings, support, language settings","langage, langue, préférence, profil, compte, apprenant, comment, changer, modifier, paramètre, soutien, paramètres de langue"
"job aid, job aids, tool, tools, work tool, work tools, abandon, quit, leave, remove, cancel, registration, course, training, event","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, laisser, se désister, se desister, supprimer, effacer, enlever, canceller, canc"
"job aid, job aids, tool, tools, work tool, work tools, how to, instructions, help, guide, navigation, general, account, use, me page, my plan, menu, actions, profile, launch, open, launching, curriculum, curricula, certification, class, course, register,","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, comment faire, how to, instructions, aide, navigation, guide, general, général"

"job aid, job aids, tool, tools, work tool, work tools, how to, instructions, help, guide, navigation, general, use, me page, my plan, menu, curriculum, curricula, certification, class, course, register, registering, find, training, browse, consult, list","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire  comment faire, how to, instructions, aide, navigation, guide, general, général"
"job aid, job aids, tool, tools, work tool, work tools, manager, managers, manager’s, team lead, lead, change, new, management, relaunch , revive, relancer,profile, account","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe"
"job aid, job aids, tool, tools, work tool, work tools, resource, resources, document, content, reading material, download, save, find, course, where, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, ressource, ressources, document, contenu, matériel de lecture, materiel"
"job aid, job aids, tool, tools, work tool, work tools, launch, can’t access, cannot access, view, old, previously completed, updated, new","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, relancer, ne peut pas accéder, acceder, pas accès, acces, visionner, visualiser"
"job aid, job aids, tool, tools, work tool, work tools, where, all, location, class creation, class administration, course creation, analytics, reports, content administrator, instructor, classroom","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil de travail, outils de travail, où, tous, emplacement, aide-memoire, aides-memoires, aide-memoires, mémoire, creation de classe, administration de classe, création de cours"
"job aid, job aids, tool, tools, work tool, work tools, person, resource, resources, trainer, activities tab, instructor, lead, leader, co-presenter, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, personne, ressource, ressources, facilitateur, instructeur, onglet activités"
"job aid, job aids, tool, tools, work tool, work tools, activities tab, standard course evaluation, general, attach, survey, publish, course, exam, test examination","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, onglet activités, activites, évaluation de cours standard, evaluation, général"
"job aid, job aids, tool, tools, work tool, work tools, related info tab, resource, resources, document, content, reading material, download, save, course, URL, file, upload","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice  onglet infos relatives, annexes, attachement, attaché, attache"
"job aid, job aids, tool, tools, work tool, work tools, course, creation, guide, guidelines, procedure, steps, delivery type, mixed, sessions, session, resource, virtual, web based, instructor-led","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, cours, administratrice, création, creation, creer, guide, lignes directrices"
"job aid, job aids, tool, tools, work tool, work tools, course, creation, guide, guidelines, procedure, steps, delivery type, scheduling details, session template, reunion, teams, Webex, Non Integrated VLE Provider","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, cours, administratrice, création, creation, creer, guide, lignes directrices"
"job aid, job aids, tool, tools, work tool, work tools, creation, guide, guidelines, procedure, steps, delivery type, content, SCORM, online, activity sequencing, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, création, creation, creer, guide, lignes directrices"
"job aid, job aids, tool, tools, work tool, work tools, creation, guide, guidelines, procedure, steps, delivery type, in person, classroom, instructor, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, création, creation, creer, guide, lignes directrices, procédur"
"job aid, job aids, tool, tools, work tool, work tools, register, registration, registrar desktop, sign up, learners, course, list, students, student, pupil, pupils, add to plan","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, enregistrer, inscrire, s’inscrire, inscription"
"job aid, job aids, tool, tools, work tool, work tools, register, registration, registrar desktop, sign up, learners, course, list, students, student, pupil, pupils, add to plan","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, enregistrer, inscrire, s’inscrire, inscription"
"job aid, job aids, tool, tools, work tool, work tools, register, registration, registrar desktop, sign up, learners, course, list, students, pupils, student, pupil, add to plan","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, enregistrer, inscrire, s’inscrire, inscription"
"job aid, job aids, tool, tools, work tool, work tools, course, close, cannot offer","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, administratrice, cours, fermer, canceller, ne peut pas offrir"
"job aid, job aids, tool, tools, work tool, work tools, learner, student, students, pupil, pupils, order, change, replace, reschedule, switch, drop, transfer, cancel","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, administratrice, apprenant, élève, élèves, eleve, eleves, commande, changer"
"job aid, job aids, tool, tools, work tool, work tools, learners, students, student, pupil, pupils, update, change, mark complete, unsuccessful, successful, close class, completion, attendance, roster, list, score, grade, passed, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, administratrice, élève, élèves, eleve, eleves, mettre à jour, mise à jour"
"job aid, job aids, tool, tools, work tool, work tools, grant credit, course, mark delivered, update status","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, Accorder crédit, credit, Accordé, accorde, cours, marquer comme livré, livrer, "
"job aid, job aids, tool, tools, work tool, work tools, course, new date, day, change date, modify, session, template, calendar","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, cours, nouvelle date, jour, journée, journée, changer, changé, change, modifier"
"Missing, administrator, instructor, looking for, searching, unable, unavailable, locate, location, locating, cannot, where, all","Manquer, manque, administrateur, instructeur, formateur, chercher, rechercher, incapable, indisponible, pas disponible, localiser, emplacement, localisation, ne peut pas, où, tous"
"Upload, content, upload, import, import file, file, Saba production, load, add, job-aid, ","Téléverser, contenu, upload, importer fichier, fichier, aide-mémoire, Saba production, chargé, mettre en ligne, ajouter, ajouté,"
"Adapt, course creation, online course, course, job-aid, export adapt, publish course, distribute, classes, design, course development,","Adapt, création de cours, cours en ligne, cours, aide-mémoire, export Adapt, publier cours, diffuser, classes, conception, développement du cours, "
"Create reports, report, report scheduling, report planning, configuration, job-aid, automated reports,","Créer des rapports, créer, rapport. Programmation des rapports, planification des rapports, configuration des rapports, aide-mémoire, rapports automatisés,"
"View, reports, export, consult, display, download, exportation, report management,","Visionner, rapports, rapport, exporter, consulter, affichage, téléchargé, exportation, gestion des rapports, format des rapports,"
"Find, field, ","Rechercher, trouver, champ, "
"Add, add owner, course, course owner, assign, select, responsible, attach, associate","Ajouter, ajouter propriétaire, proprietaire, cours, propriétaire du cours, responsable, attribuer, assigné, assigne, définir, definir, sélectionner, selectionner, joindre, attacher, associer"
"status, unsuccessful, successful, attend","statut, non réussi, non-réussi, réussi, reussi, non reussi, non-reussi, assisté, assister"
"cancel a class, cancel, class","annuler une classe, annule, annuler, classe, annuler la classe"
"add to a class, add learners to a class, add learners, class, add","ajouter à une classe, ajouter apprenants, ajouter, ajouter apprenants à une classe, classe"
"close a class, close, class, how to close a classe, how to close","fermer une classe, fermer, classe, comment fermer une classe, comment fermer"
"class roster, roster, list of learners, list, class","liste des inscrits. inscrits, liste des apprenants, liste, classe"
"record attendance, learner results, record results, results, attendance","présence, résultats, enregistrer présence, enregistrer résultats"
"instructor, navigating Saba, navigating","formateur, naviguer SABA, naviguer"
"class attachment, attachment, private class, private class attachment, class","fichier joint, fichier privé, fichier joint privé, fichier, classe"
"discontinue, discontinue a course, course","discontinuer, discontinuer un cours, cours"
"internationalize, internationalize a course, language, translate","internationaliser, internationaliser un cours, langue"
"internationalize, internationalize a class, language, add language, class, translate","internationaliser, internationaliser une classe, langue, ajouter une langue, classe"
"prerequisites, prerequisite, add prerequisites, add prerequisite, prerequisite for course. course","prérequis, ajouter prérequis, prérequis pour un cours, cours"
"add delivery types, add delivery type, delivery type, delivery type for course, virtual, blended, web-based, in-person. course","ajouter modalités pédagogiques, modalités pédagogiques, modalité, virtuelle, en personne, sur le web, mixe, cours"
"add, add completed course, completed course, ajouter", "ajouter une formation achevée, ajouter formation achevée, ajouter une formation complétée, ajouter formation complétée"



`;


// Initialize variables to hold the Title and Keywords values
var keywordsEN = [];
var keywordsFR = [];

// Function to parse the CSV data and extract Title and Keywords values
function parseCSV() {
    return new Promise((resolve, reject) => {
        Papa.parse(keywordsData, {
            header: true,
            complete: (results) => {
                keywordsEN = results.data.map(row => 
                    row['KeywordsEN']
                   
                        // Remove leading and trailing double quotes
                );

                keywordsFR= results.data.map(row => 
                    row['KeywordsFR']
                       
                        // Remove leading and trailing double quotes
                );

               
                 
                

                resolve({keywordsEN,keywordsFR}); // Resolve with the arrays
            },
            error: (error) => reject(error)
        });
    });
}





function getKeywordsEN() {
    return keywordsEN;
}

function getKeywordsFR() {
    return keywordsFR;
}

parseCSV().then(() => {
    console.log("CSV Parsed and titles and keywords ready for export");
});



window.getKeywordsEN = getKeywordsEN;
window.getKeywordsFR = getKeywordsFR;

