const keywordsData = `KeywordsEN,KeywordsFR
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, previous, courses, transfer, requirements, equivalency, training records, mandatory training curriculum, foundational training curriculum","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, précédent, cours, transfère, exigence, équivalence, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, previous, courses, transfer, requirements, equivalency, training records, mandatory training curriculum, foundational training curriculum, update","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, précédent, cours, transfère, exigence, équivalence, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, transfère, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, délai"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long, week, status, pending, complete","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, transfère, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, délai, semaine, statut, en attente, terminé"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, courses, training, mandatory training curriculum, foundational training curriculum, complete, alternate, alt, version, accessibility, accessible","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, cours, formation, curriculum de formation obligatoire, curriculum de formation fondamentale, terminé, alternative, alt, version, accessibilité, accessible"
"technical difficulties, profile, support, course, training, assistance, issue, solutions, system error, application, Saba, LMS, troubleshoot, help","difficulté technique, profil, soutien, cours, formation, assistance, problème, solutions, erreur système, application, Saba, SGA, résolution de problème, aide"
"manager, team leader, director, profile, support, course, training, assistance, issue, system error, application, Saba, LMS, help, search, cannot find, access","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, problème, erreur système, application, Saba, SGA, aide, recherche, je ne peux pas trouver, introuvable, accès"
"manager, team leader, director, profile, support, course, training, assistance, issue, system error, application, Saba, LMS, help, search, cannot find, access, privilege, role, approval, permission, need","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, problème, erreur système, application, Saba, SGA, aide, recherche, je ne peux pas trouver, introuvable, accès, privilège, rôle, approbation, autorisation, besoin"
"profile, how long, issue, session, active, application, Saba, LMS, inactivity, duration, timeout, connection, platform, disconnect","profil, combien de temps, problème, session, active, application, Saba, SGA, inactivité, durée, délai d’expiration, connexion, plateforme, déconnexion"
"manager, new, team leader, director, profile, support, course, training, assistance, issue, system error, application, Saba, LMS, help, search, cannot find, access, privilege, role, approval, permission, need, how, add, member, team, account, team dashboard","gestionnaire, nouveau, nouvelle, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, problème, erreur système, application, Saba, SGA, aide, recherche, je ne peux pas trouver, introuvable, accès, privilège, rôle, approbation, autorisation, besoin, comment, ajouter, membre, équipe, compte, console d’équipe"
"content, uploader, profile, courses, training, class, Saba, admin, administrator, upload, import, job aid, access, role, privilege, support, training material, design team, files, add, process","contenu, téléverseur, profil, cours, formation, classe, Saba, admin, administrateur, téléverser, télécharger, aide-mémoire, accès, rôle, privilège, soutien, matériel de formation, équipe de conception, fichiers, ajouter, processus"
"content, uploader, profile, courses, training, class, Saba, admin, administrator, upload, import, job aid, access, role, privilege, support, training material, design team, fichier, add, process, get","contenu, téléverseur, profil, cours, formation, classe, Saba, admin, administrateur, téléverser, télécharger, aide-mémoire, accès, rôle, privilège, soutien, matériel de formation, équipe de conception, files, ajouter, processus, obtenir"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long, week, status, pending, complete, data, completion, account","FO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, transfère, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, délai, semaine, statut, en attente, terminé, données, réussite, compte"
"manager, team leader, director, profile, support, course, training, assistance, employee, exhausted, attempt, test, passing, add, try, issue, application, Saba, LMS, help, fail, additional, exam","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, employé, épuisé, tentative, test, réussir, ajouter, essaie, problème, application, Saba, SGA, aide, échoué, supplémentaire, examen"
"manager, team leader, director, profile, support, course, training, assistance, employee, exhausted, attempt, test, passing, add, try, issue, application, Saba, LMS, help, fail, additional, exam, learner, approval, obtain, request","gestionnaire, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, employé, épuisé, tentative, test, réussir, ajouter, essaie, problème, application, Saba, SGA, aide, échoué, supplémentaire, examen, apprenant, approbation, obtenir, demande"
"MTC, FTC, curricula, curriculum, profile, mandatory, foundational, department, Dept, courses, transfer, training records, mandatory training curriculum, foundational training curriculum, update, completion, how long, status, pending, complete, data, completion, account, reconciliation, learning, indigenous","CFO, CFF, curricula, curriculum, programme d’études, profil, obligatoire, fondamentale, ministère, Dept, cours, transfert, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, mise à jour, complété, achèvement, délai, statut, en attente, terminé, données, réussite, compte, réconciliation, apprentissage, autochtone"
"account, username, login information, profile, support, course, training, assistance, issue, system, error, application, Saba, LMS, troubleshoot, help, access, login, credentials","compte, nom d’utilisateur, information de connexion, profil, soutien, cours, formation, assistance, problème, erreur, système, application, Saba, SGA, résolution de problème, aide, accès, connexion, identifiants"
"course, training, find, search, catalog, Saba, register, assistance, system, application, Saba, LMS, help, support, ways","cours, formation, trouver, recherche, catalogue, Saba, inscrire, assistance, système, application, Saba, SGA, aide, soutien, façons"
"technical difficulties, profile, support, course, training, assistance, issue, solutions, application, Saba, LMS, troubleshoot, help, launching test, launching course, account, incomplete, blocking, technical issue, progress","difficulté technique, profil, soutien, cours, formation, assistance, problème, solutions, application, Saba, SGA, résolution de problème, aide, lancer le test, lancer le cours, compte, incomplet, obstacle, problème technique, progrès"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, mandatory training curriculum, foundational training curriculum, completion, status, pending, complete, data, completion, account, technical difficulties, profile, support, course, training, assistance, issue, solutions, application, troubleshoot, help, launching course, account, incomplete, blocking, technical issue, progress","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, curriculum de formation obligatoire, curriculum de formation fondamentale, complété, statut, en attente, terminé, données, réussite, compte, difficulté technique, profil, soutien, cours, formation, assistance, problème, solutions, application, résolution de problème, aide, lancer le cours, compte, incomplet, obstacle, problème technique, progrès"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, mandatory training curriculum, foundational training curriculum, completion, status, complete, data, completion, account, profile, support, course, training, assistance, help, account, incomplete, manager, new, team leader, director, profile, support, course, training, assistance, application, Saba, LMS, help, search, access, privilege, role, member, team, account, team dashboard, report","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamentale, ministère, Dept, cours, curriculum de formation obligatoire, curriculum de formation fondamentale, complété, statut, terminé, données, réussite, compte, difficulté technique, profil, soutien, cours, formation, assistance, aide, compte, gestionnaire, nouveau, nouvelle, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, application, Saba, SGA, aide, recherche, accès, privilège, rôle, membre, équipe, compte, console d’équipe, rapport"
"MTC, FTC, curricula, curriculum, profile, mandatory, foundational, , courses, mandatory training curriculum, foundational training curriculum, completion, status, complete, data, completion, account, profile, support, course, training, assistance, help, account, incomplete, manager, new, team leader, director, profile, support, course, training, assistance, application, Saba, LMS, help, search, access, privilege, role, member, team, account, team dashboard, report, employee, analytics, accurate, accuracy","CFO, CFF, curricula, curriculum, programme d’études, profil, obligatoire, fondamentale, cours, curriculum de formation obligatoire, curriculum de formation fondamentale, complété, statut, terminé, données, réussite, compte, difficulté technique, profil, soutien, cours, formation, assistance, aide, compte, gestionnaire, nouveau, nouvelle, responsable, chef d’équipe, directeur, profil, soutien, cours, formation, application, Saba, SGA, aide, recherche, accès, privilège, rôle, membre, équipe, compte, console d’équipe, rapport, employé, analytique, précis, précision"
"course, class, link, share, sharing, deeplink, Saba, LMS, help, search, curriculum, curricula, certification, URL, send, copy link","cours, classe, lien, partage, partager, lien profond, deeplink, Saba, SGA, aide, recherche, curriculum, certification, URL, envoyer, lien copié"
"course, class, link, share, sharing, deeplink, Saba, LMS, help, search, curriculum, curricula, certification, URL, send, copy link, manager, Team lead, team","cours, classe, lien, partage, partager, lien profond, deeplink, Saba, SGA, aide, recherche, curriculum, certification, URL, envoyer, lien copié, gestionnaire, chef d’équipe, équipe"
"course, class, link, share, sharing, deeplink, Saba, LMS, help, search, curriculum, curricula, certification, URL, send, copy link, Admin, administrator, Saba, certification, curriculum, curricula, learners, guide, send","cours, classe, lien, partage, partager, lien profond, deeplink, Saba, SGA, aide, recherche, curriculum, certification, URL, envoyer, lien copié, admin, administrateur, Saba, certification, curriculum, apprenants, guider, envoyer"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, previous, courses, transfer, requirements, equivalency, training records, mandatory training curriculum, foundational training curriculum, added, manager, team lead, lead","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, précédent, cours, transfère, exigence, équivalence, dossier de formation, curriculum de formation obligatoire, curriculum de formation fondamentale, ajouter, gestionnaire, chef d’équipe, chef"
"error, profile, account, Saba, personal, information, learner, update, support, help, correct, correction, data, change, email, name, email address, need","erreur, profil, compte, Saba, personnel, information, apprenant, mise à jour, soutien, aide, corriger, correction, données, modifier, changer, nom, courriel, adresse courriel, besoin"
"return, department, Dept, learner, access, leave, account, Saba, assistance, help, absence, sick, reactivation, close, disactivate, recovery, username","retour, ministère, Dept, apprenant, accès, depart, compte, Saba, assistance, aide, absence, maladie, réactivation, fermer, désactivé, récupération, nom d’utilisateur"
"course, class, link, Saba, LMS, help, search, copy link, Saba, learners, bookmark, favorites, access, URL, website, add, hyperlink, shortcut","cours, classe, lien, Saba, SGA, aide, recherche, envoyer, lien copié, Saba, apprenants, signet, favoris, accès, URL, site web, ajouter, mettre, hyperlien, raccourci"
"class, learner, course, Saba, language, preference, support, change, update, platform, access, registration, remove registration, changer, modify","classe, apprenant, cours, Saba, langage, langue, préférence, soutien, changer, mise à jour, mettre à jour, plateforme, accès, enregistrement, retirer inscription, changer, modifier"
"manager, team leader, team lead, request, class, course, approval, learner, support, registered, registration, access, pending approval, approval request, supervisor","gestionnaire, chef d’équipe, demande, classes, cours, approbation, apprenant, soutien, enregistré, enregistrement, accès, inscription, demande d’approbation en attente, demande d’approbation, superviseur"
"manager, team leader, team lead, request, class, course, approval, learner, support, registered, registration, access, pending approval, approval request, supervisor, employee","gestionnaire, chef d’équipe, demande, classes, cours, approbation, apprenant, soutien, enregistré, enregistrement, accès, inscription, demande d’approbation en attente, demande d’approbation, superviseur, employé"
"remove, employee, team, team dashboard, manager, team leader, team lead, supervisor, my team, support, Saba, modify, how","retirer, employé, équipe, console d’équipe, gestionnaire, chef d’équipe, superviseur, mon équipe, soutien, Saba, modifier, comment"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, requirements, equivalency, mandatory training curriculum, foundational training curriculum, manager, team lead, lead, training, complete, learner, support","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, cours, exigence, équivalence, curriculum de formation obligatoire, curriculum de formation fondamentale, gestionnaire, chef d’équipe, chef, formation, complété, apprenant, soutien"
"Saba, access, personal, home, computer, government, network, off the network, internet, support, login, remote access, security, connect, connection, external, private network, private, VPN", "Saba, accès, personnel, maison, de la maison, ordinateur, gouvernement, réseau, hors réseau, internet, soutient, connexion, accès à distance, sécurité, connexion, connecter, externe, réseau privé, privé, VPN"
"evaluation, course, class, complete, pending, completed, completion status, status, completion, support, review, requirements, profile, feedback, expired, training","évaluation, cours, classe, complété, en attente, statut d’achèvement, statut, achèvement, soutien, vérification, exigences, profil, rétroaction, expiré, formation"
"employee, team, team dashboard, manager, team leader, team lead, supervisor, my team, support, Saba, modify, how, approve, learning, training, course, class, learner, registration, reject, pending approval","employé, équipe, console d’équipe, gestionnaire, chef d’équipe, superviseur, mon équipe, soutien, Saba, modifier, comment, approuver, apprentissage, formation, cours, classe, apprenant, inscription, rejeter, en attente d’approbation"
"Saba, iService, support, access, information, page, intranet, help, tools, assistance, online resources","Saba, iService, soutien, accès, information, page, intranet, aide, outils, assistance, ressource en ligne"
"Saba, course, admin, administrator, instructor, facilitator, role, privilege, steps, support, help, to take, training","Saba, cours, admin, administrateur, formateur, facilitateur, rôle, privilège, étapes, soutien, aide, de suivre, formation"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, requirements, equivalency, mandatory training curriculum, foundational training curriculum, manager, team lead, lead, training, complete, learner, support, information, employee","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, cours, exigence, équivalence, curriculum de formation obligatoire, curriculum de formation fondamentale, gestionnaire, chef d’équipe, chef, formation, complété, apprenant, soutien, information, employé, responsable"
"job aid, job-aid, tool, manager, team lead, team leader, lead, help, support, resources","aide mémoire, aide-mémoire, outils, gestionnaire, chef d’équipe, chef, aide, soutien, ressources, responsable"
"MTC, FTC, curricula, curriculum, CSPS, Canada School of Public Service, profile, mandatory, foundational, department, Dept, courses, requirements, mandatory training curriculum, foundational training curriculum, manager, team, lead, training, completion, learner, support, information, employee, data, team dashboard","CFO, CFF, curricula, curriculum, programme d’études, EFPC, École de la fonction publique du Canada, profil, obligatoire, fondamental, ministère, Dept, cours, exigence, curriculum de formation obligatoire, curriculum de formation fondamentale, gestionnaire, équipe, formation, achèvement, apprenant, soutien, information, employé, responsable, données, console d’équipe"
"proxy, assign, manager, director, actions, on my behalf, authorization, process, support, instructions, role, privilege, reports, executive, EX, act as","mandataire, assigner, gestionnaire, directeur, actions, en mon nom, autorisation, processus, soutien, instructions, rôle, privilège, rapport, cadre, exécutif, EX, agir en tant que"
"proxy, assign, manager, director, actions, on my behalf, authorization, process, support, instructions, role, privilege, reports, executive, EX, act","mandataire, assigner, gestionnaire, directeur, actions, en mon nom, autorisation, processus, soutien, instructions, rôle, privilège, rapport, cadre, exécutif, EX, agir en tant que"
"team member, team, learning, activity, plan, learning plan, employee, learner, manager, team lead, team leader, course, class, training, how, process, add","membre de l’équipe, équipe, apprentissage, activité, plan, plan d’apprentissage, employé, apprenant, gestionnaire, responsable, chef d’équipe, cours, classe, formation, comment, processus, ajouter"
"learner, job aid, job-aid, find, support, tools","apprenant, aide mémoire, aide-mémoire, trouver, soutien, outils"
"waitlist, accept, reject, drop, seat, learner, available, approval, request, pending, registration, how to, class, course","liste d’attente, accepter, rejeter, abandonner, siège, apprenant, disponible, approbation, demande, en attente, inscription, comment, classe, cours"
"access, Saba, first time, account, profile, learner, login, instructions, credentials, support, help, assistance, steps, password, username, session, PS, PeopleSoft, new","accès, Saba, première fois, compte, profil, apprenant, connexion, instructions, identifiants, soutien, aide, assistance, étapes, mot de passe, nom d’utilisateur, session, PS, PeopleSoft, nouveau"
"accessibility, activate, turn on, support, feature, assistance, interface, user, learner, profile, account, accessibility mode, tools","accessibilité, activer, soutien, fonctionnalité, assistance, interface, utilisateur, apprenant, profil, compte, mode d’accessibilité, outils"
"external, course, class, outside of Saba, externally, add, tool, how, completed, completed learning, learning, process, learner, completed course, training","externe, cours, classe, a l’extérieur de Saba, ajouter, outil, comment, complété, apprentissage complété, apprentissage, processus, apprenant, cours complété, formation"
"language, preference, profile, account, learner, how, change, update, settings, support, language settings","langage, langue, préférence, profil, compte, apprenant, comment, changer, modifier, paramètre, soutien, paramètres de langue"
"drop, class, course, learner, instructions, process, support, how, enrollment, roster, waitlist, cancel, withdraw, delete, remove","désister, abandonner, classes, cours, apprenant, instructions, processus, soutien, comment, inscription, liste des inscrits, liste d’attente, canceller, annuler, enlever, supprimer"
"how, navigate, within Saba, learners, menu, support, resources, tools, catalog, course, class, instructions, interface, navigation, learning catalog, learning, training, launch, actions, register, help","comment, naviguer, dans Saba, apprenant, menu, soutien, ressources, outils, catalogue, cours, classe, instructions, interface, navigation, catalogue de formation, formation, apprentissage, lancer, actions, inscriptions, aide"
"certificate, print, course, class, register, profile, account, learner, completed, learning, training, how, export, instructions, completion, status, download, support, achievement","certificat, imprimer, impression, cours, classe, inscrit, profil, compte, apprenant, complété, apprentissage, formation, comment, exporter, instructions, complétion, statut, télécharger, soutien, achèvement"
"how, navigate, within Saba, learners, menu, support, resources, tools, catalog, course, class, instructions, interface, navigation, learning catalog, learning, training, launch, actions, register, help, course catalog, filters, search","comment, naviguer, dans Saba, apprenant, menu, soutien, ressources, outils, catalogue, cours, classe, instructions, interface, navigation, catalogue de formation, formation, apprentissage, lancer, actions, inscriptions, aide, catalogue de cours, filtres, rechercher, chercher"
"update, profile, account, manager, team lead, team leader, modify, add, remove, learner, change, how, user profile, support, new","mise à jour, mettre à jour, compte, profil, gestionnaire, responsable, chef d’équipe, modifier, ajouter, retirer, enlever, apprenant, changer, comment, profil d’utilisateur, soutien, nouveau"
"class, course, attachment, attached files, files, PDF, Word, document, view, download, resources, how, tools, job aid, job-aid, work tools, reading, material, save","classe, cours, attachement, ficher joint, fichier, PDF, Word, document, visualiser, voir, télécharger, ressources, comment, outils, aide mémoire, aide-mémoire, outil de travail, lecture, matériel, enregistrer"
"content, relaunch, launch, course, class, learner, completed, previously, access, retake, view, updated, new","contenu, relancer, lancer, cours, classe, apprenant, complété, précédemment, accès, accéder, reprendre, visualiser, visionner, voir, mise à jour, nouveau"
"Admin, administrator, find, where, job aid, job-aids, help, support, access, resources, material, training, guides, tools, administration, class creation, course, class, creation","Admin, administrateur, trouver, où, aide mémoire, aide-mémoire, aide, soutien, accès, ressources, matériel, formation, guides, outils, administration, création de classes, cours, classe, création"
"add, facilitator, instructor, class, course, Admin, administrator, role, privilege, remove, person, resource, trainer, how","ajouter, facilitateur, instructeur, classe, cours, Admin, administrateur, rôle, privilège, retirer, enlever, personne, ressource, formateur, comment"
"add, evaluation, post evaluation, instructions, how, support, class, course, training, remove, update, admin, administrator, tools, course evaluation","ajouter, évaluation, évaluation après cours, instructions, comment, soutien, classe, cours, formation, retirer, enlever, mise à jour, mettre à jour, admin, administrateur, outil, évaluation de cours"
"add, attachment, instructions, how, support, class, course, training, remove, update, admin, administrator, tools, file, upload, download, resources, material, document, PDF, Word","ajouter, attachement, pièces jointes, instructions, comment, soutien, classe, cours, formation, retirer, enlever, mise à jour, mettre à jour, admin, administrateur, outil, fichier, télécharger, téléverser, ressources, matériel, document, PDF, Word"
"job aid, job aids, tool, tools, work tool, work tools, course, creation, guide, guidelines, procedure, steps, delivery type, mixed, sessions, session, resource, virtual, web based, instructor-led","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, cours, administratrice, création, creation, creer, guide, lignes directrices"
"class, virtual class, virtual, instructor led, instructor-led, how, create, creation, class creation, job aid, job-aid, instructions, support, Admin, administrator, tools","classes, virtuelle, classe virtuelle, facilité, facilité par un formateur, comment, créer, création, création de classe, aide mémoire, aide-mémoire, instructions, soutien, Admin, administrateur, outils"
"class, web-based class, Web, self-paced, paced, how, create, creation, class creation, job aid, job-aid, instructions, support, Admin, administrator, tools","classes, sur le Web, Web, a son propre rythme, rythme, comment, créer, création, création de classe, aide mémoire, aide-mémoire, instructions, soutien, Admin, administrateur, outils"
"class, instructor, instructor-led, in person, facilitated, how, create, creation, class creation, job aid, job-aid, instructions, support, Admin, administrator, tools, in class","classes, instructeur, formateur, en personne, tutorée, facilité, comment, créer, création, création de classe, aide mémoire, aide-mémoire, instructions, soutien, Admin, administrateur, outils, en salle de classe"
"class, web-based class, Web, self-paced, paced, how, attach, content, job aid, job-aid, instructions, support, Admin, administrator, tools","classes, sur le Web, Web, a son propre rythme, rythme, comment, attacher, contenu, aide mémoire, aide-mémoire, instructions, soutien, Admin, administrateur, outils"
"class, add, roster, learner, participant, Admin, administrator, course admin, course administrator, job aid, job-aid, tools, list, register, registration","classe, ajouter, liste des inscrits, apprenant, participant, Admin, administrateur, administrateur de cours, aide mémoire, aide-mémoire, outils, liste, inscrire, inscription"
"class, assign, learning, training, registrar desktop, activity, course, learner, tools, help, register, Admin, administrator","classe, assigner, affecter, apprentissage, formation, bureau du chargé d’inscriptions, activité, cours, apprenant, outils, aide, inscrire, Admin, administrateur"
"class, cancel, course, learner, roster, Admin, administrator, help, support","classes, canceller, annuler, cours, apprenant, liste des inscrits, Admin, administrateur, aide, soutien"
"class, roster, registration, learner, modify, update, change, Admin, administrator, course","classe, liste des inscrits, inscription, apprenant, modifier, mise à jour, mette à jour, changer, Admin, administrateur, cours"
"class, learner, status, roster, registration, completion, course, record, support, help, Admin, administrator, how","classe, apprenant, statut, liste des inscrits, inscription, achèvement, cours, enregistrer, soutien, aide, Admin, administrateur, comment"
"class, close, delivered, roster, Admin, Administrator, how","classe, fermé, fermer, livré, liste des inscrits, Admin, administrateur, comment,livrée"
"class, reschedule, course, Admin, administrator, how, support, help, new date","class, re céduler, reporter, cours, Admin, administrateur, comment, soutien, aide, nouvelle date"
"class, roster, find, locate, search, Admin, administrator, how, help, support","classe, liste des inscrits, trouver, localiser, chercher, Admin, administrateur, comment, aide, soutien"
"Upload, content, upload, import, import file, file, Saba production, load, add, job-aid, ","Téléverser, contenu, upload, importer fichier, fichier, aide-mémoire, Saba production, chargé, mettre en ligne, ajouter, ajouté,"
"Adapt, publish, how, Admin, administrator, created on Adapt, course, design, publish course","Adapt, publier, comment, Admin, administrateur, créés sur Adapt, cours, conception, publier un cours"
"Create reports, report, report scheduling, report planning, configuration, job-aid, automated reports,","Créer des rapports, créer, rapport. Programmation des rapports, planification des rapports, configuration des rapports, aide-mémoire, rapports automatisés,"
"View, reports, export, consult, display, download, exportation, report management,","Visionner, rapports, rapport, exporter, consulter, affichage, téléchargé, exportation, gestion des rapports, format des rapports,"
"Find, field, ","Rechercher, trouver, champ, "
"Add, add owner, course, course owner, assign, select, responsible, attach, associate","Ajouter, ajouter propriétaire, proprietaire, cours, propriétaire du cours, responsable, attribuer, assigné, assigne, définir, definir, sélectionner, selectionner, joindre, attacher, associer"
"status, unsuccessful, successful, attend","statut, non réussi, non-réussi, réussi, reussi, non reussi, non-reussi, assisté, assister"
"cancel a class, cancel, class","annuler une classe, annule, annuler, classe, annuler la classe"
"add to a class, add learners to a class, add learners, class, add","ajouter à une classe, ajouter apprenants, ajouter, ajouter apprenants à une classe, classe"
"close a class, close, class, how to close a classe, how to close","fermer une classe, fermer, classe, comment fermer une classe, comment fermer"
"class roster, roster, list of learners, list, class","liste des inscrits. inscrits, liste des apprenants, liste, classe"
"record attendance, learner results, record results, results, attendance","présence, résultats, enregistrer présence, enregistrer résultats"
"instructor, navigating Saba, navigating","formateur, naviguer SABA, naviguer"
"class attachment, attachment, private class, private class attachment, class","fichier joint, fichier privé, fichier joint privé, fichier, classe"
"discontinue, discontinue a course, course","discontinuer, discontinuer un cours, cours"
"internationalize, internationalize a course, language, translate","internationaliser, internationaliser un cours, langue"
"internationalize, internationalize a class, language, add language, class, translate","internationaliser, internationaliser une classe, langue, ajouter une langue, classe"
"prerequisites, prerequisite, add prerequisites, add prerequisite, prerequisite for course. course","prérequis, ajouter prérequis, prérequis pour un cours, cours"
"add delivery types, add delivery type, delivery type, delivery type for course, virtual, blended, web-based, in-person. course","ajouter modalités pédagogiques, modalités pédagogiques, modalité, virtuelle, en personne, sur le web, mixe, cours"
"add, add completed course, completed course, ajouter", "ajouter une formation achevée, ajouter formation achevée, ajouter une formation complétée, ajouter formation complétée"



`;


// Initialize variables to hold the Title and Keywords values
var keywordsEN = [];
var keywordsFR = [];

// Function to parse the CSV data and extract Title and Keywords values
function parseCSV() {
    return new Promise((resolve, reject) => {
        Papa.parse(keywordsData, {
            header: true,
            complete: (results) => {
                keywordsEN = results.data.map(row => 
                    row['KeywordsEN']
                   
                        // Remove leading and trailing double quotes
                );

                keywordsFR= results.data.map(row => 
                    row['KeywordsFR']
                       
                        // Remove leading and trailing double quotes
                );

               
                 
                

                resolve({keywordsEN,keywordsFR}); // Resolve with the arrays
            },
            error: (error) => reject(error)
        });
    });
}





function getKeywordsEN() {
    return keywordsEN;
}

function getKeywordsFR() {
    return keywordsFR;
}

parseCSV().then(() => {
    console.log("CSV Parsed and titles and keywords ready for export");
});



window.getKeywordsEN = getKeywordsEN;
window.getKeywordsFR = getKeywordsFR;

