const keywordsData = `KeywordsEN,KeywordsFR
"peoplesoft, password, pass, pwd, change, update, access, new, login, log in, connect, first","peoplesoft, mot de passe, mdp, reinitialiser, mettre à jour, acces, accès, new, login, log in, connect, first"
"essential, etc, curricula, courses, classes, transfer, start over, profile, repeat, redo, equivalence, missing, CFE","curriculum, curricula, complété, complete, completer, essentielle, cfe, obligatoire, EDSC, cours, classes, transférer, transfert, transferer, recommencer, profil, répéter, repeter, refaire, de nouveau, équivalence,"
"essential, etc, curriculum, School of Public Service, school, curricula, courses, classes, transfer, start over, repeat, redo, transfer, equivalence, missing, CFE","curriculum, essentielle, cfe, ecole de la fonction publique du Canada, EFPC, ecole, répéter, repeter, refaire, de nouveau, transfert, transféré, transfere, équivalence, equivalence, manque, manquant manquantes, ETC"
"essential, etc, curriculum, School of Public Service, CSPS, school, equivalent, equivalence, transfer, completed, how much time, how long, completions, profile, equivalence, missing, CFE","curriculum, essentielle, cfe, ecole de la fonction publique du Canada, EFPC, ecole, équivalence, equivalence, transfert, transférer, transferer, complété, complete, combien de temps, achèvements, achevements, delai, profil, équivalence, equivalence, manqu"
"essential, etc, curriculum, School of Public Service, CSPS, school, equivalent, equivalence, transfer, completed, how much time, how long, completions, profile, equivalence, missing, CFE","curriculum, essentielle, cfe, ecole de la fonction publique du Canada, EFPC, ecole, équivalence, equivalence, transfert, transférer, transferer, complété, complete, combien de temps, achèvements, achevements, delai, profil, équivalence, equivalence, manqu"
"essential, etc, curriculum, alternative, equivalence, equivalence, accessibility, accessible, CFE","curriculum, essentielle, cfe, version, accessible, équivalence, equivalence, accessibilité, accessible, accessibilite, ETC"
"technical, difficulties, problem, problems, tickets, national desk, national service, national service desk, NSD, client services, help, does not work ","Problèmes techniques, problemes, ticket, demande, billets, difficultes, probleme, problemes, inforservice, infoservice national, NSD, service clientèle, clientele, aide, ne fonctionne pas "
"manager, managers, manager’s, team lead, lead","gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe, responsable, responsables, equipe"
"manager, managers, manager’s, team lead, lead","gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe, responsable, responsables, equipe"
"Remember Me, login, login page, Session duration,  duration, Session","Mémoriser mon profil,  connexion, page de connexion, Durée de la session, session"
"manager, managers, manager’s, team lead, lead, find me","gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe, responsable, responsables, equipe, me trouver"
" Upload, Content, Administrators, Process, Add, Add content, Content upload, Upload content, Upload files, Files, Job aid, SharePoint, Design team, Instruction, Content administrator, Teams, Import, Load, Transfer, Upload / Put online, Insert files, - Sub","Téléversement, contenu, administrateurs,  Processus,  Ajouter,  Ajouter contenu,  Téléversement de contenu, Upload,  Upload contenu,  Téléverser fichiers, aide- mémoire, SharePoint, équipe de conception, instruction,  Administrateur de contenu."
"administrator access, administrator, admin permissions, permissions, administrator rights, account, content acces, access, interface, guide,Parameter, create account, role, list, existing account, content administrator, role permission, obtain","Accès administrateur,administrateur,  Permissions admin,  Permissions,  Droits administrateur, Compte, contenu acces, access, accès, interface, guide,Paramètre, créer compte, rôle, liste, compte existant"
"completed, complete, learning, etc, adding, done, finished, add, external, outside, Saba, update, learning, course, class, update, CFE, completee, complété, complete, formation, cfe, complété, achevé, acheve, fini, réussi, reussi, ajouter, ajoute, ajouté, externe, en dehors, Saba, cours, mettre à jour, mettre a jour, mise à jour, mise a jour, ETC, access, accéder, accédez"
"attempts, attempt, exhausted, tries, test, additional, unsuccessful,   manager, managers, manager’s, team lead, lead, exam, examination","epuise, tentatives, essai, essais, examen, chances, supplementaire, supplémentaire, supplémentaires, terminé, termine, échoué, echoue, échouer, echouer, coulé, couler, coule,   gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe"
"attempts, attempt, exhausted, tries, test  manager, managers, manager’s, team lead, lead, exam, examination","épuisé, tentative, tentatives, essai, essais, examen, test, exam, gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe, responsable, responsables, équipe"
"essential, etc, curriculum, reconciliation, equivalence, equivalent, transfer, completed, completions, profile, missing, completion, completed, CFE","curriculum, essentielle, cfe, reconciliation, enregistrée, enregistree, enregistrer, capturé, capturée, capturee, équivalence, equivalence, transfert, transférer, transferer, complété, complete, profil, equivalence, manque, manquant, manquantes"
"Login, log in, first, user, name, connect, connection, connexion, forgot, lost, remember, information, access, accessing","Connecter, connexion, première, premiere, premier, connection, oublié, oubli, oublier, perdu, perdre, souvenir, information, accéder, accéder, accède"
"Search function, searching, where, location, training, classes, courses, web-based, virtual, when, finding, help, information, registration, options","Fonction de recherche, rechercher, où, lieu, emplacement, formation, classes, cours, en ligne, sur le web, virtuel, quand, trouver, aide, information, inscription, options"
"Incomplete, unfinished, partial, difficulties,  obstacles, complications, hurdles, faulty, glitch, error, issues, technical, not letting me,  preventing, blocking,  impractical, blocked, stuck, forward,  advancing, progress, advance, problem, impossible,","Incomplet, inachevé, inacheve, partiel, difficultés, difficultes, difficile, obstacles, complications, défectueux, défectueux, pépin, pepin, erreur, problèmes, probleme, technique, ne pas me laisser faire, empêcher, bloquer, impraticable, bloqué, bloque,"
"technical, difficulties, problem, problems, client services, customer, help, does not work","ecole, completer, complété, complete, problèmes techniques, probleme, problèmes, service clientèle, clientele, aide, ne fonctionne pas"
"manager, managers, manager’s, team lead, lead, report, analytics, statistics, stats, incomplete, information, employees, team, reports, direct, essential, etc, curriculum, completed, complete, completions, profile, CFE  ","gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe, responsable, responsables, equipe, analytique, statistiques, achèvements, stats, incomplet, complété, complet, complète, information, employés, employées, employée, directe, rapports"
"manager, managers, manager’s, team lead, lead, report, analytics, statistics, stats, incomplete, information, employees, team, reports, direct, incorrect, false, inaccurate ","gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe, responsable, responsables, equipe, analytique, statistiques, achèvements, stats, incomplet, complété, complet, complete, information, employés, employées, employée, directe, rapports, data, fausse"
"Class, course, curriculum, curricula, certification, share, send, link, URL, web address, address, directly, hyperlink, address, learning, event, training, direct, lead, find, learner, student, sign up, register, program, path    Links, hyperlinks","Classe, cours, curriculum, cursus, programme, chemin, feuille de route, certification, partager, envoyer, lien, URL, adresse web, directement, direct, hyperlien, adresse, addresse, apprentissage, événement, evenement, formation, training, mener, trouver,"
"Class, course, curriculum, curricula, certification, share, send, link, URL, web address, address, directly, hyperlink, address, learning, event, training, direct, lead, find, learner, student, sign up, register, program, path, team, employees, manager","Classe, cours, curriculum, cursus, programme, chemin, feuille de route, certification, partager, envoyer, lien, URL, adresse web, directement, direct, hyperlien, adresse, addresse, apprentissage, événement, evenement, formation"
"Class, course, curriculum, curricula, certification, share, send, link, URL, web address, address, directly, hyperlink, address, learning, event, training, direct, lead, find, learner, student, sign up, register, program, path, administrator, deeplink","Classe, cours, curriculum, cursus, programme, chemin, feuille de route, certification, partager, envoyer, lien, URL, adresse web, directement, direct, hyperlien, adresse, addresse, apprentissage, événement, evenement, formation, training, mener, trouver,"
"Essential training curriculum, automatic add to the profile, manager training not added, curriculum not visible, update training profile, manual add, essential training curriculum problem, ETC managers, integration, inclusion","Curriculum de formation essentielle, ajout automatique profil, formation gestionnaire non ajoutée, curriculum non visible,  mise à jour profil formation,  ajout manuel,  problème de  Curriculum de formation essentielle,  CFE gestionnaires, intégration"
"Correct, errors, personal information, name errors, email address, incorrect personal information, change name, profile, change email address, correct account information, mistakes, update, fixing, wrong, rectifying","Corriger, erreurs, informations personnelles, erreurs nom, adresse email, informations personnelles incorrectes, modifier nom, profil, changer adresse électronique, corriger informations compte, erreurs, mettre à jour, réparer, mal, rectifier"
"reactivate Saba account, reactivate profile after absence, Saba account inactive, resume Saba access, reopen account after absence, reactivate user access, restore Saba account, account disabled absence, reset Saba account, return absence inactive account","retour d'absence réactiver compte,  réactivation compte Saba,  réactiver profil après absence,  compte Saba inactif,  reprendre accès Saba,  réouverture compte après absence, réactivation accès utilisateur, restaurer compte Saba, compte désactivé absence"
"desactivate, deleted, account, reactivate, access, close, support contact, nsd, recover, find, viewed, resume","Désactivation, supprimé, compte, réactivation, accès, fermeture, contact support, ISN, récupérer, retrouver, consulté, reprendre"
"link, bookmark, original, hyperlink, direct link, add, procedure, shortcut, links, url, saved, reference, web","Lien, signet, original, hyperlien, lien direct, ajouter, procédure, raccourci, liens, url, sauvegardé, référence, web, marque-pages"
"Registration, course, class, English, French, bilingual, preferred language, abandon, abandon registration, register, owner, contact details, training, classroom, membership, registration, session, leave, unregister, remove registration, contact","Inscription, cours, classe, francais, anglais, bilingue, langue préféré, abandonner, abandonner inscription, inscrire, propriétaire, coordonnées,  formation, salle de cours, adhésion, enregistrement, session, quitter, désinscrire, retirer inscription"
"Manager, team leader, supervisor, approval, approved, profile, update, manager, ISN, approve, interim manager, new request, don't give up, email to national service desk, national infoservice","Gestionnaire, chef d’équipe, superviseur, approbation, approuvé, profil, mettre à jour, responsable, ISN, approuver, gestionnaire intérim, nouvelle demande, n’abandonnez pas, courriel l’infoservice national"
"Employee, employees, Manager, team leader, supervisor, approval, approved, profile, update, manager, NSD, approve, interim manager, new request, don't give up, National Service Desk email, director","Employé, employée, employés, employées, Gestionnaire, chef d’équipe, superviseur, approbation, approuvé, profil, mettre à jour, responsable, ISN, approuver, gestionnaire intérim, nouvelle demande, n’abandonnez pas, courriel l’infoservice national"
"Session, minutes, minutes of activity, session time, session duration, automatic logout, logout.","Session, minutes, minutes d’activité, temps de session, durée de session, déconnexion automatique, déconnexion, inactivité, période, politique, fermeture, fin de session"
"Session, minutes, minutes of activity, session time, session duration, automatic logout, logout.","Session, minutes, minutes d’activité, temps de session, durée de session, déconnexion automatique, déconnexion, inactivité, période, politique, fermeture, fin de session"
"Word, password, Saba, update, expiration, regularly","Mot, mots, passe, mot de passe, regulierement, régulierement, Saba, mise a jour, expiration"
"Added, add, add, manager, managers, team leader, modify, modified, responsible, remove, withdrawn, employee, employees","ajouté, ajouter, ajoute, gestionnaire, gestionnaires, chef d’équipe, modifier, modifié, responsable, retirer, retiré, employé, employée, employés, employées"
"Training, Trainings, Completed, complete, Curriculum, Essential training, specific training, manager, admin, Portal, Learning, College@ESDC, learn","Formation, formations,  completé, completer, curriculum, formation essentielle, formation spécifiques, responsable, gestionnaire, portail, apprentissage, Collège@EDSC, apprennant"
"Network, connect, connect to Saba, Remote, Home, Connection, External, VPN, Private network, Access, Personal computer, Réseau, connecter, connecter à Saba, distance, maison, connexion, externe, VPN, accès, accès, ordinateur personnel"
"Course, evaluation, profile, training, feedback, fill out, complete, pending, expire","Cours, évaluation, profil, formation, rétroaction, remplir, compléter, attente, expirer"
"Remember Me, login, login page, log in, Session duration, duration, Session, connexion, connect, connection","Mémoriser mon profil, connexion, page de connexion, Durée de la session, session, connecter"
"Approve, Approved, reject, Rejected, Authorization, Approval, learning","Approuver, approuvé, rejeter, rejeté, autorisation, approbation, autorisé, processus d’approbation, formation"
"Information, info, roles, iService, administrator, manager, team leader, learner, administrator, instructor, page, help, understand, general, intranet","Information, info, rôles, roles, iService, administrateur, manager, chef d'équipe, apprenant, administrateur, instructeur, page, aider, comprendre, général, intranet"
"Information, info, role, administrator, admin, instructor, design team, class, roster, completion, manage, facilitate, registration, status, register, manage, mark complete, facilitate","Information, info, rôle, role, administrateur, admin, instructeur, équipe de conception, equipe, classe, liste, inscrits, inscription, inscrire, statut, achèvement, achevement, marquer complété, complete, gérer, gérer, faciliter"
"Information, info, role, administrator, admin, instructor, design team, class, roster, completion, manage, facilitate, registration, status, register, manage, mark complete, facilitate","Information, info, rôle, role, administrateur, admin, instructeur, équipe de conception, equipe, classe, liste, inscrits, inscription, inscrire, statut, achèvement, achevement, marquer complété, complete, gérer, gérer, faciliter"
"Indigenous Awareness and Reconciliation, information, training, mandatory, CSPS,  Occupational Health and Safety and Hazard Prevention Training for Employees, Security 101,  Access to Information and Privacy (ATIP): It’s Everybody’s Business ,  Doing Thin","Indigenous Awareness, Formation sur la Sensibilisation aux cultures autochtones et la réconciliation,  Formation sur la santé et la sécurité au travail et la prévention des risques pour les employés, Sécurité 101, La protection des renseignements personne"
"job aid, job aids, tool, tools, work tool, work tools, where, all, location, manager, managers, manager’s, team lead, lead","aide-mémoire, aides-mémoires, aide-mémoires, aide, mémoire, job aid, outil, outils, outil de travail, outils de travail, où, ou, tous, emplacement, aide-memoire, aides-memoires, aide-memoires, mémoire, gestionnaire, gestionnaires, chef, chef d'équipe, che"
"job aid, job aids, tool, tools, work tool, tools Access, Job aid, report, data, team curriculum, completion report, ETC","Accès, aide-mémoire, rapport, rapport achèvement, curriculum, CFE, données, équipe"
"Job aid, desk aid, learning, instruction, execute, run, reports, executive managers, assign, assigned, proxi, action, role","Aide-mémoire, job aid, aide mémoire, aide mémoire, apprentissage, instruction, exécuter, rapports, cadres exécutifs, Assigner, assigné, mandataire, action"
"Job aid, learning, instruction, execute, run, reports, executive managers, assign, assigned, proxi, action, role, act","Aide-mémoire, apprentissage, instruction, exécuter, rapports, cadres exécutifs, Assigner, assigné, mandataire, action"
"Added, add, add activity, assignment, training, activity, plan, team, member","Ajouté, ajouter, ajouter activité, assignation, formation, Activité, activités, plan, membre, équipe"
"job aid, job aids, tool, tools, work tool, work tools, where, all, location, students, pupils, participants","aide-mémoire, aides-mémoires, aide, mémoire, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, où, ou, tous, emplacement, aide-memoire, aides-memoires, aide-memoires, mémoire, élèves, étudiants, participants"
"job aid, job aids, tool, tools, work tool, work tools, waitlist, class","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, siège, siege, classe"
"job aid, job aids, tool, tools, work tool, work tools  saba, account, new, PeopleSoft, password, pw","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire  saba, conte, comte, accès, premiere, premier, nouveau, PeopleSoft, mot de passe"
"job aid, job aids, tool, tools, work tool, work tools, accessible","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, activé, active, accessible"
"job aid, job aids, tool, tools, work tool, work tools, done, finished, add, external, outside, Saba, update, learning, course, class, update, history ","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, complété, achevé, acheve, fini, réussi, reussi, ajouter, ajoute, ajouté"
"job aid, job aids, tool, tools, work tool, work tools, French, English, language, change, account, log in, connection, login, session, setting, settings","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, français, francais, anglais, langue, langage, changer, compte, connecter"
"job aid, job aids, tool, tools, work tool, work tools, peoplesoft, reset, pass, pwd, change, update, account, modify, modification","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, peoplesoft, réinitialiser, reinitialiser, mdp, mettre à jour, mettre a jour"
"job aid, job aids, tool, tools, work tool, work tools, abandon, quit, leave, remove, cancel, registration, course, training, event","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, laisser, se désister, se desister, supprimer, effacer, enlever, canceller, canc"
"job aid, job aids, tool, tools, work tool, work tools, how to, instructions, help, guide, navigation, general, account, use, me page, my plan, menu, actions, profile, launch, open, launching, curriculum, curricula, certification, class, course, register,","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, comment faire, how to, instructions, aide, navigation, guide, general, général"
"job aid, job aids, tool, tools, work tool, work tools, completion, complete, save, prove, proof, transfer, share, new department, send, attach, join, download, upload, import","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, complété, complete, complet, achevement, achevé, acheve, remettre, preuve"
"job aid, job aids, tool, tools, work tool, work tools  peoplesoft, pass, pwd, change, update, account, modify, modification, cannot access, login, log in, connection, enter, let me in ","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, peoplesoft, reinitialiser, mdp, mettre à jour, mettre a jour, mise à jour"
"job aid, job aids, tool, tools, work tool, work tools, how to, instructions, help, guide, navigation, general, use, me page, my plan, menu, curriculum, curricula, certification, class, course, register, registering, find, training, browse, consult, list","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire  comment faire, how to, instructions, aide, navigation, guide, general, général"
"job aid, job aids, tool, tools, work tool, work tools, manager, managers, manager’s, team lead, lead, change, new, management, relaunch , revive, relancer,profile, account","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, gestionnaire, gestionnaires, chef, chef d'équipe, chefs, chefs d'équipe"
"job aid, job aids, tool, tools, work tool, work tools, resource, resources, document, content, reading material, download, save, find, course, where, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, ressource, ressources, document, contenu, matériel de lecture, materiel"
"job aid, job aids, tool, tools, work tool, work tools, launch, can’t access, cannot access, view, old, previously completed, updated, new","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, relancer, ne peut pas accéder, acceder, pas accès, acces, visionner, visualiser"
"job aid, job aids, tool, tools, work tool, work tools, where, all, location, class creation, class administration, course creation, analytics, reports, content administrator, instructor, classroom","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil de travail, outils de travail, où, tous, emplacement, aide-memoire, aides-memoires, aide-memoires, mémoire, creation de classe, administration de classe, création de cours"
"job aid, job aids, tool, tools, work tool, work tools, person, resource, resources, trainer, activities tab, instructor, lead, leader, co-presenter, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, personne, ressource, ressources, facilitateur, instructeur, onglet activités"
"job aid, job aids, tool, tools, work tool, work tools, activities tab, standard course evaluation, general, attach, survey, publish, course, exam, test examination","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, onglet activités, activites, évaluation de cours standard, evaluation, général"
"job aid, job aids, tool, tools, work tool, work tools, related info tab, resource, resources, document, content, reading material, download, save, course, URL, file, upload","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice  onglet infos relatives, annexes, attachement, attaché, attache"
"job aid, job aids, tool, tools, work tool, work tools, course, creation, guide, guidelines, procedure, steps, delivery type, mixed, sessions, session, resource, virtual, web based, instructor-led","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, cours, administratrice, création, creation, creer, guide, lignes directrices"
"job aid, job aids, tool, tools, work tool, work tools, course, creation, guide, guidelines, procedure, steps, delivery type, scheduling details, session template, reunion, teams, Webex, Non Integrated VLE Provider","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, cours, administratrice, création, creation, creer, guide, lignes directrices"
"job aid, job aids, tool, tools, work tool, work tools, creation, guide, guidelines, procedure, steps, delivery type, content, SCORM, online, activity sequencing, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, création, creation, creer, guide, lignes directrices"
"job aid, job aids, tool, tools, work tool, work tools, creation, guide, guidelines, procedure, steps, delivery type, in person, classroom, instructor, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, création, creation, creer, guide, lignes directrices, procédur"
"job aid, job aids, tool, tools, work tool, work tools, register, registration, registrar desktop, sign up, learners, course, list, students, student, pupil, pupils, add to plan","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, enregistrer, inscrire, s’inscrire, inscription"
"job aid, job aids, tool, tools, work tool, work tools, register, registration, registrar desktop, sign up, learners, course, list, students, student, pupil, pupils, add to plan","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, enregistrer, inscrire, s’inscrire, inscription"
"job aid, job aids, tool, tools, work tool, work tools, register, registration, registrar desktop, sign up, learners, course, list, students, pupils, student, pupil, add to plan","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, administratrice, enregistrer, inscrire, s’inscrire, inscription"
"job aid, job aids, tool, tools, work tool, work tools, course, close, cannot offer","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, administratrice, cours, fermer, canceller, ne peut pas offrir"
"job aid, job aids, tool, tools, work tool, work tools, learner, student, students, pupil, pupils, order, change, replace, reschedule, switch, drop, transfer, cancel","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, administratrice, apprenant, élève, élèves, eleve, eleves, commande, changer"
"job aid, job aids, tool, tools, work tool, work tools, learners, students, student, pupil, pupils, update, change, mark complete, unsuccessful, successful, close class, completion, attendance, roster, list, score, grade, passed, course","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, administratrice, élève, élèves, eleve, eleves, mettre à jour, mise à jour"
"job aid, job aids, tool, tools, work tool, work tools, grant credit, course, mark delivered, update status","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, Accorder crédit, credit, Accordé, accorde, cours, marquer comme livré, livrer, "
"job aid, job aids, tool, tools, work tool, work tools, course, new date, day, change date, modify, session, template, calendar","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, mémoire, cours, nouvelle date, jour, journée, journée, changer, changé, change, modifier"
"job aid, job aids, tool, tools, work tool, work tools, course, virtual, web based, web-based, blended, instructor-led, instructor led, list, learners, learner, students, student, pupil, pupils","aide-mémoire, aide, mémoire, aides-mémoires, aide-mémoires, job aids, outil, outils, outil de travail, outils de travail, aide-memoire, aides-memoires, aide-memoires, memoire, cours, administratrice, mixte, mix, blended, virtuelle, virtuel, sur le web"
"Missing, administrator, instructor, looking for, searching, unable, unavailable, locate, location, locating, cannot, where, all","Manquer, manque, administrateur, instructeur, formateur, chercher, rechercher, incapable, indisponible, pas disponible, localiser, emplacement, localisation, ne peut pas, où, tous"
"Upload, content, upload, import, import file, file, Saba Development, load, add, job-aid","Téléverser, contenu, upload, importer fichier, fichier, aide-mémoire, Saba développement, chargé, mettre en ligne, ajouter, ajouté, "
"Upload, content, upload, import, import file, file, Saba production, load, add, job-aid, ","Téléverser, contenu, upload, importer fichier, fichier, aide-mémoire, Saba production, chargé, mettre en ligne, ajouter, ajouté,"
"Adapt, course creation, online course, course, job-aid, export adapt, publish course, distribute, classes, design, course development,","Adapt, création de cours, cours en ligne, cours, aide-mémoire, export Adapt, publier cours, diffuser, classes, conception, développement du cours, "
"Create reports, report, report scheduling, report planning, configuration, job-aid, automated reports,","Créer des rapports, créer, rapport. Programmation des rapports, planification des rapports, configuration des rapports, aide-mémoire, rapports automatisés,"
"View, reports, export, consult, display, download, exportation, report management,","Visionner, rapports, rapport, exporter, consulter, affichage, téléchargé, exportation, gestion des rapports, format des rapports,"
"Find, field, ","Rechercher, trouver, champ, "
"Add, add owner, course, course owner, assign, select, responsible, attach, associate","Ajouter, ajouter propriétaire, proprietaire, cours, propriétaire du cours, responsable, attribuer, assigné, assigne, définir, definir, sélectionner, selectionner, joindre, attacher, associer"
"status, unsuccessful, successful, attend","statut, non réussi, non-réussi, réussi, reussi, non reussi, non-reussi, assisté, assister"
"cancel a class, cancel, class","annuler une classe, annule, annuler, classe, annuler la classe"
"add to a class, add learners to a class, add learners, class, add","ajouter à une classe, ajouter apprenants, ajouter, ajouter apprenants à une classe, classe"
"close a class, close, class, how to close a classe, how to close","fermer une classe, fermer, classe, comment fermer une classe, comment fermer"
"class roster, roster, list of learners, list, class","liste des inscrits. inscrits, liste des apprenants, liste, classe"
"record attendance, learner results, record results, results, attendance","présence, résultats, enregistrer présence, enregistrer résultats"
"instructor, navigating Saba, navigating","formateur, naviguer SABA, naviguer"
"class attachment, attachment, private class, private class attachment, class","fichier joint, fichier privé, fichier joint privé, fichier, classe"
"discontinue, discontinue a course, course","discontinuer, discontinuer un cours, cours"
"internationalize, internationalize a course, language, translate","internationaliser, internationaliser un cours, langue"
"internationalize, internationalize a class, language, add language, class, translate","internationaliser, internationaliser une classe, langue, ajouter une langue, classe"
"prerequisites, prerequisite, add prerequisites, add prerequisite, prerequisite for course. course","prérequis, ajouter prérequis, prérequis pour un cours, cours"
"add delivery types, add delivery type, delivery type, delivery type for course, virtual, blended, web-based, in-person. course","ajouter modalités pédagogiques, modalités pédagogiques, modalité, virtuelle, en personne, sur le web, mixe, cours"
"add, add completed course, completed course, ajouter", "ajouter une formation achevée, ajouter formation achevée, ajouter une formation complétée, ajouter formation complétée"
`;


// Initialize variables to hold the Title and Keywords values
var keywordsEN = [];
var keywordsFR = [];

// Function to parse the CSV data and extract Title and Keywords values
function parseCSV() {
    return new Promise((resolve, reject) => {
        Papa.parse(keywordsData, {
            header: true,
            complete: (results) => {
                keywordsEN = results.data.map(row => 
                    row['KeywordsEN']
                   
                        // Remove leading and trailing double quotes
                );

                keywordsFR= results.data.map(row => 
                    row['KeywordsFR']
                       
                        // Remove leading and trailing double quotes
                );

               
                 
                

                resolve({keywordsEN,keywordsFR}); // Resolve with the arrays
            },
            error: (error) => reject(error)
        });
    });
}





function getKeywordsEN() {
    return keywordsEN;
}

function getKeywordsFR() {
    return keywordsFR;
}

parseCSV().then(() => {
    console.log("CSV Parsed and titles and keywords ready for export");
});



window.getKeywordsEN = getKeywordsEN;
window.getKeywordsFR = getKeywordsFR;

