name: Sync JSON from OneDrive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download JSON from SharePoint
        run: |
          curl -L "https://014gc.sharepoint.com/sites/ILMS-SIGA/Other/Saba%20Reporting%20Working%20Group/02.%20Client%20Data%20Requests/02.%20Client%20Files/SABA%20Report/VATAllQuestion.json" -o data.json

      - name: Move file into repo folder
        run: |
          mkdir -p data
          mv data.json data/data.json

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/data.json
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "Sync JSON from SharePoint"
          git push
